/**
 * Copyright (c) 2024-2025 Huawei Device Co., Ltd.
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// Autogenerated file -- DO NOT EDIT!

#ifndef ES2PANDA_PUBLIC_ES2PANDA_LIB
#define ES2PANDA_PUBLIC_ES2PANDA_LIB

// Switch off the linter for C header
// NOLINTBEGIN
//

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <uchar.h>

#ifdef __cplusplus
extern "C" {
#endif

#define ES2PANDA_LIB_VERSION 1

typedef struct es2panda_Config es2panda_Config;
typedef struct es2panda_Context es2panda_Context;

typedef struct es2panda_variantDoubleCharArrayBool {
    int index;
    union {
        double d;
        char *c;
        bool b;
    } variant;
} es2panda_variantDoubleCharArrayBool;

enum es2panda_variantIndex {
    DOUBLE = 0,
    CHAR = 1,
    BOOL = 2,
};

typedef struct es2panda_Program es2panda_Program;
typedef struct es2panda_ExternalSource es2panda_ExternalSource;
typedef struct es2panda_ArkTsConfig es2panda_ArkTsConfig;
typedef struct es2panda_AstNode es2panda_AstNode;
typedef struct es2panda_FunctionSignature es2panda_FunctionSignature;
typedef struct es2panda_SourcePosition es2panda_SourcePosition;
typedef struct es2panda_SourceRange es2panda_SourceRange;
typedef struct es2panda_SrcDumper es2panda_SrcDumper;
typedef struct es2panda_AstDumper es2panda_AstDumper;
typedef struct es2panda_LabelPair es2panda_LabelPair;
typedef struct es2panda_ScriptFunctionData es2panda_ScriptFunctionData;
typedef struct es2panda_ImportSource es2panda_ImportSource;
typedef struct es2panda_Signature es2panda_Signature;
typedef struct es2panda_SignatureInfo es2panda_SignatureInfo;
typedef struct es2panda_CheckerContext es2panda_CheckerContext;
typedef struct es2panda_ResolveResult es2panda_ResolveResult;
typedef struct es2panda_ValidationInfo es2panda_ValidationInfo;
typedef struct es2panda_Type es2panda_Type;
typedef struct es2panda_TypeRelation es2panda_TypeRelation;
typedef struct es2panda_IndexInfo es2panda_IndexInfo;
typedef struct es2panda_GlobalTypesHolder es2panda_GlobalTypesHolder;
typedef struct es2panda_ObjectDescriptor es2panda_ObjectDescriptor;
typedef struct es2panda_Variable es2panda_Variable;
typedef struct es2panda_Scope es2panda_Scope;
typedef struct es2panda_ScopeFindResult es2panda_ScopeFindResult;
typedef struct es2panda_BindingProps es2panda_BindingProps;
typedef struct es2panda_Declaration es2panda_Declaration;
typedef struct es2panda_RecordTable es2panda_RecordTable;
typedef struct es2panda_BoundContext es2panda_BoundContext;
typedef struct es2panda_AstVisitor es2panda_AstVisitor;
typedef struct es2panda_AstVerifier es2panda_AstVerifier;
typedef struct es2panda_VerifierMessage es2panda_VerifierMessage;
typedef struct es2panda_CodeGen es2panda_CodeGen;
typedef struct es2panda_VReg es2panda_VReg;
typedef struct es2panda_IRNode es2panda_IRNode;
typedef struct es2panda_ErrorLogger es2panda_ErrorLogger;
typedef struct es2panda_VerificationContext es2panda_VerificationContext;
typedef void (*NodeTraverser)(es2panda_AstNode *);
typedef es2panda_AstNode *(*NodeTransformer)(es2panda_AstNode *);
typedef bool (*NodePredicate)(es2panda_AstNode *);
typedef es2panda_Variable *(*PropertyProcessor)(es2panda_Variable *, es2panda_Type *);
typedef void (*PropertyTraverser)(const es2panda_Variable *);
typedef void (*ClassBuilder)(es2panda_AstNode **nodes, size_t size);
typedef void (*MethodBuilder)(es2panda_AstNode **statements, size_t sizeStatements, es2panda_AstNode **expression,
                              size_t sizeExpression, es2panda_Type **type);
typedef void (*ClassInitializerBuilder)(es2panda_AstNode **statements, size_t sizeStatements,
                                        es2panda_AstNode **expression, size_t sizeExpression);

typedef struct es2panda_DynamicImportData {
    const es2panda_AstNode *import;
    const es2panda_AstNode *specifier;
    es2panda_Variable *variable;
} es2panda_DynamicImportData;

enum es2panda_ContextState {
    ES2PANDA_STATE_NEW,
    ES2PANDA_STATE_PARSED,
    ES2PANDA_STATE_SCOPE_INITED,
    ES2PANDA_STATE_BOUND,
    ES2PANDA_STATE_CHECKED,
    ES2PANDA_STATE_LOWERED,
    ES2PANDA_STATE_ASM_GENERATED,
    ES2PANDA_STATE_BIN_GENERATED,

    ES2PANDA_STATE_ERROR
};
typedef enum es2panda_ContextState es2panda_ContextState;
// CC-OFFNXT(G.INC.08) project code style
#include "generated/es2panda_lib/es2panda_lib_enums.inc"

struct es2panda_Impl {
    int version;

    es2panda_Config *(*CreateConfig)(int argc, char const *const *argv);
    void (*DestroyConfig)(es2panda_Config *config);

    es2panda_Context *(*CreateContextFromFile)(es2panda_Config *config, char const *source_file_name);
    es2panda_Context *(*CreateContextFromString)(es2panda_Config *config, const char *source, char const *file_name);
    es2panda_Context *(*ProceedToState)(es2panda_Context *context, es2panda_ContextState state);  // context is consumed
    void (*DestroyContext)(es2panda_Context *context);

    es2panda_ContextState (*ContextState)(es2panda_Context *context);
    char const *(*ContextErrorMessage)(es2panda_Context *context);

    es2panda_Program *(*ContextProgram)(es2panda_Context *context);
    char const *(*ExternalSourceName)(es2panda_ExternalSource *e_source);
    es2panda_Program **(*ExternalSourcePrograms)(es2panda_ExternalSource *e_source, size_t *len_p);
    void (*AstNodeForEach)(es2panda_AstNode *ast, void (*func)(es2panda_AstNode *, void *), void *arg);

#define SET_NUMBER_LITERAL_DECL(name, type) bool (*SetNumberLiteral##name)(es2panda_AstNode * node, type new_value)

    SET_NUMBER_LITERAL_DECL(Int, int32_t);
    SET_NUMBER_LITERAL_DECL(Long, int64_t);
    SET_NUMBER_LITERAL_DECL(Double, double);
    SET_NUMBER_LITERAL_DECL(Float, float);

#undef SET_NUMBER_LITERAL_DECL

#define CREATE_UPDATE_NUMBER_LITERAL_IMPL(num, type)                                   \
    es2panda_AstNode *(*CreateNumberLiteral##num)(es2panda_Context * ctx, type value); \
    es2panda_AstNode *(*UpdateNumberLiteral##num)(es2panda_Context * ctx, es2panda_AstNode * original, type value)

    CREATE_UPDATE_NUMBER_LITERAL_IMPL(, int32_t);
    CREATE_UPDATE_NUMBER_LITERAL_IMPL(1, int64_t);
    CREATE_UPDATE_NUMBER_LITERAL_IMPL(2, double);
    CREATE_UPDATE_NUMBER_LITERAL_IMPL(3, float);

#undef CREATE_UPDATE_NUMBER_LITERAL_IMPL

    void *(*AllocMemory)(es2panda_Context *context, size_t numberOfElements, size_t sizeOfElement);
    es2panda_SourcePosition *(*CreateSourcePosition)(es2panda_Context *context, size_t index, size_t line);
    es2panda_SourceRange *(*CreateSourceRange)(es2panda_Context *context, es2panda_SourcePosition *start,
                                               es2panda_SourcePosition *end);
    size_t (*SourcePositionIndex)(es2panda_Context *context, es2panda_SourcePosition *position);
    size_t (*SourcePositionLine)(es2panda_Context *context, es2panda_SourcePosition *position);
    es2panda_SourcePosition *(*SourceRangeStart)(es2panda_Context *context, es2panda_SourceRange *range);
    es2panda_SourcePosition *(*SourceRangeEnd)(es2panda_Context *context, es2panda_SourceRange *range);
    void (*LogTypeError)(es2panda_Context *context, const char *errorMsg, es2panda_SourcePosition *pos);
    void (*LogWarning)(es2panda_Context *context, const char *warnMsg, es2panda_SourcePosition *pos);
    void (*LogSyntaxError)(es2panda_Context *context, const char *errorMsg, es2panda_SourcePosition *pos);
    es2panda_Scope *(*AstNodeFindNearestScope)(es2panda_Context *ctx, es2panda_AstNode *node);
    es2panda_Scope *(*AstNodeRebind)(es2panda_Context *ctx, es2panda_AstNode *node);
    void (*AstNodeRecheck)(es2panda_Context *ctx, es2panda_AstNode *node);
    Es2pandaEnum (*Es2pandaEnumFromString)(es2panda_Context *ctx, const char *str);
    char *(*Es2pandaEnumToString)(es2panda_Context *ctx, Es2pandaEnum id);
    es2panda_AstNode *(*DeclarationFromIdentifier)(es2panda_Context *ctx, es2panda_AstNode *node);

// CC-OFFNXT(G.INC.08) project code style
#include "generated/es2panda_lib/es2panda_lib_decl.inc"
};

struct es2panda_Impl const *es2panda_GetImpl(int version);

// NOLINTEND

#ifdef __cplusplus
}
#endif

#endif
